# Base CRS setup (copied from example, trimmed)
# Paranoia Level
SecAction "id:900000,phase:1,nolog,pass,t:none,setvar:tx.paranoia_level=1"

# Executing paranoia level in phase 2 as well
SecAction "id:900001,phase:2,nolog,pass,t:none,setvar:tx.paranoia_level=1"

# Enforce blocking by anomaly score (already set in modsecurity.conf)