ARG NGINX_CERTBOT_IMAGE=jonasal/nginx-certbot:6.2.0-nginx1.31.4
FROM ${NGINX_CERTBOT_IMAGE} AS build
ARG NGINX_VERSION=1.31.4
ARG MODSECURITY_VERSION=v3.0.16
ARG MODSECURITY_NGINX_VERSION=v1.0.4

RUN apt-get update && apt-get install -y --no-install-recommends \
    autoconf automake build-essential ca-certificates curl git libcurl4-openssl-dev \
    libgeoip-dev liblmdb-dev libmaxminddb-dev libpcre2-dev libtool libxml2-dev \
    libyajl-dev pkg-config zlib1g-dev \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src
RUN git clone --branch "${MODSECURITY_VERSION}" --depth 1 https://github.com/owasp-modsecurity/ModSecurity.git \
 && cd ModSecurity && git submodule update --init --recursive && ./build.sh \
 && ./configure --prefix=/usr && make -j"$(nproc)" && make install

RUN set -eux; installed="$(nginx -v 2>&1 | sed 's#^nginx version: nginx/##')"; \
    test "${installed}" = "${NGINX_VERSION}"; \
    curl -fsSLO "https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz"; \
    tar -xzf "nginx-${NGINX_VERSION}.tar.gz"; \
    git clone --branch "${MODSECURITY_NGINX_VERSION}" --depth 1 https://github.com/owasp-modsecurity/ModSecurity-nginx.git; \
    cd "nginx-${NGINX_VERSION}"; args="$(nginx -V 2>&1 | sed -n 's/^configure arguments: //p')"; \
    eval "./configure ${args} --with-compat --add-dynamic-module=/usr/src/ModSecurity-nginx"; \
    make modules; test -s objs/ngx_http_modsecurity_module.so

FROM ${NGINX_CERTBOT_IMAGE}
RUN apt-get update && apt-get install -y --no-install-recommends \
      libcurl4t64 libgeoip1t64 liblmdb0 libmaxminddb0 libxml2 libyajl2 \
 && rm -rf /var/lib/apt/lists/* \
 && mkdir -p /usr/lib/nginx/modules /etc/nginx/modules-enabled /etc/modsecurity
COPY --from=build /usr/lib/libmodsecurity.so* /usr/lib/
COPY --from=build /usr/src/nginx-1.31.4/objs/ngx_http_modsecurity_module.so /usr/lib/nginx/modules/
RUN printf '%s\n' 'load_module /usr/lib/nginx/modules/ngx_http_modsecurity_module.so;' > /etc/nginx/modules-enabled/50-modsecurity.conf && ldconfig
EXPOSE 80 443
